services:
  - type: web
    name: mini-jira-backend
    env: node
    repo: https://github.com/Milind74/Bug-Tracker.git
    rootDir: ./bug-tracker-server
    buildCommand: ls -la && pwd && npm --version && node --version && npm install && ls -la node_modules && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true