services:
  - type: web
    name: mini-jira-backend
    env: node
    repo: https://github.com/Milind74/Bug-Tracker.git
    rootDir: ./bug-tracker-server
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://your-frontend-url.vercel.app